#theme: minima
theme: jekyll-theme-minimal
# --- Required options --- #

# Name of website
title: ğŸ’» âœ’ï¸ ğŸ“„ğŸŒŸ
description: Andriy Kotko's CV represents a journey of professional growth and a steadfast commitment to excellence in frontend development.

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
logo: '/assets/img/kotko_avatar.png'

# --- Footer social media links --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: 'kotkoa@gmail.com'
  telephone: +34 647-185-406
  #facebook: deanattali
  github: https://github.com/Kotkoa
  twitter: kotkoa
# patreon: DeanAttali
# youtube: c/daattali
#  medium: yourname
#  reddit: yourname
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  spotify: yourname
#  discord: invite/invite_code or users/userid

